version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-229-210-93.compute-1.amazonaws.com
            database: dd0j8dmmmvb8cm
            user: fcacibzebfkaaa
            password: 64080778c9c0a466654b1d82856bf725162d38337ec4b5a8bda526eaca5fe548
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true